### ISSUE TITLE
Custom Bee's crash when looking up there recipie in NEI.

### ISSUE THREAD

**Issue by SyriiAdvent** [bdew-minecraft/gendustry#103]
[15:59:36] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 6/22/15 3:59 PM
Description: Updating screen events

java.lang.RuntimeException: Config value 'Genetics' is missing
    at scala.sys.package$.error(package.scala:27)
    at net.bdew.lib.recipes.gencfg.ConfigSection$$anonfun$1.apply(ConfigSection.scala:23)
    at net.bdew.lib.recipes.gencfg.ConfigSection$$anonfun$1.apply(ConfigSection.scala:23)
    at scala.collection.Map$WithDefault.default(Map.scala:53)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:59)
    at net.bdew.lib.recipes.gencfg.ConfigSection.getRaw(ConfigSection.scala:31)
    at net.bdew.lib.recipes.gencfg.ConfigSection.getSection(ConfigSection.scala:43)
    at net.bdew.gendustry.machines.mutatron.MachineMutatron$.mutatronOverrides$lzycompute(MachineMutatron.scala:36)
    at net.bdew.gendustry.machines.mutatron.MachineMutatron$.mutatronOverrides(MachineMutatron.scala:33)
    at net.bdew.gendustry.nei.MutatronHandler.canShowMutation(MutatronHandler.scala:70)
    at net.bdew.gendustry.nei.MutatronHandler$$anonfun$loadCraftingRecipes$1$$anonfun$applyOrElse$3.apply(MutatronHandler.scala:117)
    at net.bdew.gendustry.nei.MutatronHandler$$anonfun$loadCraftingRecipes$1$$anonfun$applyOrElse$3.apply(MutatronHandler.scala:117)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
    at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
    at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
    at net.bdew.gendustry.nei.MutatronHandler$$anonfun$loadCraftingRecipes$1.applyOrElse(MutatronHandler.scala:117)
    at net.bdew.gendustry.nei.MutatronHandler$$anonfun$loadCraftingRecipes$1.applyOrElse(MutatronHandler.scala:113)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214)
    at scala.Option.collect(Option.scala:259)
    at net.bdew.gendustry.nei.MutatronHandler.loadCraftingRecipes(MutatronHandler.scala:113)
    at net.bdew.gendustry.nei.MutatronHandler.loadCraftingRecipes(MutatronHandler.scala:32)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
    at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    at codechicken.nei.recipe.GuiRecipe.func_73869_a(GuiRecipe.java:80)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:276)
    at org.multimc.onesix.OneSixLauncher$1.run(OneSixLauncher.java:351)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at scala.sys.package$.error(package.scala:27)
    at net.bdew.lib.recipes.gencfg.ConfigSection$$anonfun$1.apply(ConfigSection.scala:23)
    at net.bdew.lib.recipes.gencfg.ConfigSection$$anonfun$1.apply(ConfigSection.scala:23)
    at scala.collection.Map$WithDefault.default(Map.scala:53)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:59)
    at net.bdew.lib.recipes.gencfg.ConfigSection.getRaw(ConfigSection.scala:31)
    at net.bdew.lib.recipes.gencfg.ConfigSection.getSection(ConfigSection.scala:43)
    at net.bdew.gendustry.machines.mutatron.MachineMutatron$.mutatronOverrides$lzycompute(MachineMutatron.scala:36)
    at net.bdew.gendustry.machines.mutatron.MachineMutatron$.mutatronOverrides(MachineMutatron.scala:33)
    at net.bdew.gendustry.nei.MutatronHandler.canShowMutation(MutatronHandler.scala:70)
    at net.bdew.gendustry.nei.MutatronHandler$$anonfun$loadCraftingRecipes$1$$anonfun$applyOrElse$3.apply(MutatronHandler.scala:117)
    at net.bdew.gendustry.nei.MutatronHandler$$anonfun$loadCraftingRecipes$1$$anonfun$applyOrElse$3.apply(MutatronHandler.scala:117)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
    at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
    at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
    at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
    at net.bdew.gendustry.nei.MutatronHandler$$anonfun$loadCraftingRecipes$1.applyOrElse(MutatronHandler.scala:117)
    at net.bdew.gendustry.nei.MutatronHandler$$anonfun$loadCraftingRecipes$1.applyOrElse(MutatronHandler.scala:113)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214)
    at scala.Option.collect(Option.scala:259)
    at net.bdew.gendustry.nei.MutatronHandler.loadCraftingRecipes(MutatronHandler.scala:113)
    at net.bdew.gendustry.nei.MutatronHandler.loadCraftingRecipes(MutatronHandler.scala:32)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
    at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    at codechicken.nei.recipe.GuiRecipe.func_73869_a(GuiRecipe.java:80)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput

**Comment by SyriiAdvent** [comment]
https://gist.github.com/leagris/fbb1a1dfbb5f890c8379

**Comment by leagris** [comment]
Faund cause:

In commit e2f2cd0c752d78ef886c5bdec30628eede934f5d @bdew Added a Genetics section to tuning.cfg

Unfortunately, when upgrading from older Gendustry with config overrides, missing this `Genetics` section in `overrides/tuning.cfg` cause this crash.

User side fix:
Add this missing section to overrides/tuning.cfg with:

``` YAML
cfg Genetics {
    cfg MutatronOverrides {

        // Keys are species UID
        // Values are: ENABLED/DISABLED/REQUIREMENTS
        // ENABLED will allow that mutation without checking requirements (this is the default)
        // DISABLED will disallow that mutation in the mutatron
        // REQUIREMENTS will check normal breeding requirements (only valid for bee species)

        "forestry.speciesLeporine" = REQUIREMENTS
        "forestry.speciesMerry" = REQUIREMENTS
        "forestry.speciesTipsy" = REQUIREMENTS
        "forestry.speciesTricky" = REQUIREMENTS
    }
}
```

@bdew would it be possible to have configuration updates handled even in overrides?

**Comment by bdew** [comment]
I don't have means to merge config files in overrides folder, it's your responsibility to update them if you use them.

From the docs:

> There are 3 ways to provide custom configuration extensions:
> - Create a file in <minecraft>/config/gendustry named <whatever>.cfg – This is the recommended method
> - Extract any of the files from the jar into <minecraft>/config/gendustry/overrides and edit them there – You will be need to manually update them when the mod updates
> - Edit the files directly in the JAR – This is the least recommended method
