### ISSUE TITLE
Crash in Gendustry when adding custom Bees

### ISSUE THREAD

**Issue by ken-noland** [bdew-minecraft/gendustry#182]
Minecraft Version: 1.10.2
Gendustry Version : 1.6.4.17
Forestry Version: 1,10,2-5.2.9.241

Getting a crash inside Gendustry when using the default Gendustry Example for providing custom bees : https://github.com/bdew/gendustry/blob/mc1710/example_configs/example_bees.cfg

Here's the callstack : 

java.lang.IllegalArgumentException: No enum constant forestry.api.apiculture.EnumBeeChromosome.NOCTURNAL
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_101]
        at forestry.api.apiculture.EnumBeeChromosome.valueOf(EnumBeeChromosome.java:25) ~[EnumBeeChromosome.class:?]
        at net.bdew.gendustry.custom.BeeSpecies$$anonfun$getTemplate$3.apply(BeeSpecies.scala:151) ~[BeeSpecies$$anonfun$getTemplate$3.class:?]
        at net.bdew.gendustry.custom.BeeSpecies$$anonfun$getTemplate$3.apply(BeeSpecies.scala:150) ~[BeeSpecies$$anonfun$getTemplate$3.class:?]
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778) ~[TraversableLike$WithFilter$$anonfun$foreach$1.class:?]
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221) ~[HashMap$HashMap1.class:?]
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428) ~[HashMap$HashTrieMap.class:?]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777) ~[TraversableLike$WithFilter.class:?]
        at net.bdew.gendustry.custom.BeeSpecies.getTemplate(BeeSpecies.scala:150) ~[BeeSpecies.class:?]
        at net.bdew.gendustry.custom.CustomContent$$anonfun$registerTemplates$1.apply(CustomContent.scala:112) ~[CustomContent$$anonfun$registerTemplates$1.class:?]
        at net.bdew.gendustry.custom.CustomContent$$anonfun$registerTemplates$1.apply(CustomContent.scala:112) ~[CustomContent$$anonfun$registerTemplates$1.class:?]
        at scala.collection.immutable.List.foreach(List.scala:383) ~[List.class:?]
        at net.bdew.gendustry.custom.CustomContent$.registerTemplates(CustomContent.scala:112) ~[CustomContent$.class:?]
        at net.bdew.gendustry.Gendustry$.postInit(Gendustry.scala:118) ~[Gendustry$.class:?]
        at net.bdew.gendustry.Gendustry.postInit(Gendustry.scala) ~[Gendustry.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595) ~[forge-1.10.2-12.18.1.2073-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:793) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by ken-noland** [comment]
I'm away from my desk at the moment, but should I try Forestry 247 or 248? I can see you've updated to the latest forge which includes the new power API, and I think this version of Forestry doesn't cover that yet.

**Comment by bdew** [comment]
No need. Looks like a bug on my side, will fix soon(tm).

**Comment by ken-noland** [comment]
I'm new at this, so forgive me if it's obvious... Is this because of building Gendustry with a different version of the Forestry API? Just curious because I'm going to start getting into modding soon, but I'm mainly a C++ guy :)

**Comment by bdew** [comment]
Hmm... you are using the old examples for 1.7.10? There are some changes for 1.10, see here: https://github.com/bdew/gendustry/tree/mc1.10.2/example_configs

The error happens because the old examples refer to a chromosome that was renamed. I should probably make that error more user friendly...

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
