### ISSUE TITLE
Console spam- Massive log size

### ISSUE THREAD

**Issue by Moonlightneo** [bdew-minecraft/gendustry#202]
The game still runs, and plays fine to my knowledge, however i get a ton of console spam, that causes my launcher window to freeze up and become completely unresponsive until forced to shut down via task manager. Being as the logs are literally over 1 gigabyte, it's not exactly possible to share the entirety, so if you need more than this bit of code eh..maybe we can work it out, else, here you go.
Also, just based on my scanning, i can't tell if this is caused by gendustry/bdlib, or Blockdrops, so if i'm in the wrong place just lemme know, i'm only certain that removing gendustry solves the problem.
This is also a custom modpack i've been trying to work together and make stable (at least, in the confines of what minecraft can even call stable), so it's pretty heavy considering.

`[Client thread/WARN] [bdlib/blockdrops]: Error retrieving TE
java.lang.NullPointerException
	at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
	at net.minecraft.world.World.func_175625_s(World.java:2402) ~[aid.class:?]
	at net.bdew.lib.block.HasTE$$anonfun$1.apply(HasTE.scala:59) ~[HasTE$$anonfun$1.class:?]
	at net.bdew.lib.block.HasTE$$anonfun$1.apply(HasTE.scala:59) ~[HasTE$$anonfun$1.class:?]
	at scala.util.Try$.apply(Try.scala:191) ~[Try$.class:?]
	at net.bdew.lib.block.HasTE$class.getTE(HasTE.scala:59) [HasTE$class.class:?]
	at net.bdew.gendustry.machines.apiary.BlockApiary$.getTE(BlockApiary.scala:24) [BlockApiary$.class:?]
	at net.bdew.lib.block.BlockKeepData$class.getSavedBlock(KeepData.scala:38) [BlockKeepData$class.class:?]
	at net.bdew.gendustry.machines.apiary.BlockApiary$.getSavedBlock(BlockApiary.scala:24) [BlockApiary$.class:?]
	at net.bdew.lib.block.BlockKeepData$class.getDrops(KeepData.scala:44) [BlockKeepData$class.class:?]
	at net.bdew.gendustry.machines.apiary.BlockApiary$.getDrops(BlockApiary.scala:24) [BlockApiary$.class:?]
	at net.bdew.gendustry.machines.apiary.BlockApiary$.getDrops(BlockApiary.scala:24) [BlockApiary$.class:?]
	at mrriegel.blockdrops.Plugin.getList(Plugin.java:109) [Plugin.class:?]
	at mrriegel.blockdrops.Plugin.getRecipes(Plugin.java:85) [Plugin.class:?]
	at mrriegel.blockdrops.BlockDrops.postInit(BlockDrops.java:128) [BlockDrops.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by bdew** [comment]
This error seems to be caused by BlockDrops JEI plugin, i've opened an issue on their bug tracker - MrRiegel/BlockDrops#25

**Comment by bdew** [comment]
Hm, looking at the stacktrace this happens during initialization, it might be the first error in your log but i don't think it should repeat after the game is loaded... Can you check further in the log if the repeated errors are the same?

**Comment by KidsDontPlay** [comment]
do you use latest version?

**Comment by Moonlightneo** [comment]
It doesn't spam the log post load, no, and i've scrolled through alot of it and they look identical so i'm assuming the other several hundred errors are the same, the game runs fine once loaded just this particular error clogs up the launcher (Which i prefer to remain visible, as it allows me to more easily determine potential problems with mods, rather than having to open the file in some odd app just because the file is ginormous)

As for version, i used curse to make the pack and try to keep the mods up to date where possible.
Blockdrops ver: https://puu.sh/sHtf1/cc8a0a03f6.png
Gendustry ver: https://puu.sh/sHtie/56108ee5af.png
Bdlib ver: https://puu.sh/sHtDp/6e48d858fe.png

Edit: Actually i stand corrected, the error seems to differentiate slightly, heres another clip
`[Client thread/WARN] [bdlib/blockdrops]: Error retrieving TE
java.lang.NullPointerException
	at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
	at net.minecraft.world.World.func_175625_s(World.java:2402) ~[aid.class:?]
	at net.bdew.lib.block.HasTE$$anonfun$1.apply(HasTE.scala:59) ~[HasTE$$anonfun$1.class:?]
	at net.bdew.lib.block.HasTE$$anonfun$1.apply(HasTE.scala:59) ~[HasTE$$anonfun$1.class:?]
	at scala.util.Try$.apply(Try.scala:191) ~[Try$.class:?]
	at net.bdew.lib.block.HasTE$class.getTE(HasTE.scala:59) [HasTE$class.class:?]
	at net.bdew.gendustry.machines.transposer.BlockTransposer$.getTE(BlockTransposer.scala:20) [BlockTransposer$.class:?]
	at net.bdew.lib.block.BlockKeepData$class.getSavedBlock(KeepData.scala:38) [BlockKeepData$class.class:?]
	at net.bdew.gendustry.machines.transposer.BlockTransposer$.getSavedBlock(BlockTransposer.scala:20) [BlockTransposer$.class:?]
	at net.bdew.lib.block.BlockKeepData$class.getDrops(KeepData.scala:44) [BlockKeepData$class.class:?]
	at net.bdew.gendustry.machines.transposer.BlockTransposer$.getDrops(BlockTransposer.scala:20) [BlockTransposer$.class:?]
	at net.bdew.gendustry.machines.transposer.BlockTransposer$.getDrops(BlockTransposer.scala:20) [BlockTransposer$.class:?]
	at mrriegel.blockdrops.Plugin.getList(Plugin.java:109) [Plugin.class:?]
	at mrriegel.blockdrops.Plugin.getRecipes(Plugin.java:85) [Plugin.class:?]
	at mrriegel.blockdrops.BlockDrops.postInit(BlockDrops.java:126) [BlockDrops.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by bdew** [comment]
No that's more or less the same error. I think i have a solution, testing a fix right now.

**Comment by bdew** [comment]
Added a workaround in bdew/bdlib@13fd4414bd1251c5cb4c2e5519f5e86a49d2a5ed

Please try this build of bdlib: https://jenkins.bdew.net/job/bdlib-1.10.2/19/artifact/build/libs/bdlib-1.12.2.19-mc1.10.2.jar

**Comment by Moonlightneo** [comment]
Seems to have worked https://puu.sh/sHxk4/faafc8b165.png
Currently loaded, launcher is unfrozen and working as intended, thanks for the quick fix 👍

**Comment by bdew** [comment]
Yay
