### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by ireallyrox** [bdew-minecraft/gendustry#211]
My world keeps crashing after about 5-10 minutes of play and from what i can read from the crash report it has something to do with gendustry and magicbees. Can anyone help?

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 09/02/17 6:48 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at magicbees.bees.allele.flowerProvider.FlowerProviderArsMagicaFlower.growFlower(FlowerProviderArsMagicaFlower.java:84)
	at magicbees.bees.allele.flowerProvider.FlowerProviderArsMagicaFlower.growFlower(FlowerProviderArsMagicaFlower.java:61)
	at forestry.apiculture.flowers.FlowerRegistry.growFlower(FlowerRegistry.java:260)
	at forestry.apiculture.genetics.Bee.plantFlowerRandom(Bee.java:785)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:242)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:224)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TileApiary.scala:138)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:130)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:130)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at net.bdew.gendustry.misc.DataSlotErrorStates.withSuspendedUpdates(DataSlotErrorStates.scala:82)
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2.apply$mcV$sp(TileApiary.scala:130)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by bdew** [comment]
Crash in Magic Bees code, when it's trying to do something with AM flowers... Nothing i can do about this from my side.

I'd tell you to report it there, but i don't think the 1.7.10 version is being maintained anymore.

**Comment by ireallyrox** [comment]
Ok, thank you for looking at it.
