### ISSUE TITLE
Client crush

### ISSUE THREAD

**Issue by takilazy** [bdew-minecraft/gendustry#23]
---- Minecraft Crash Report ----
// You're mean.

Time: 15.05.14 20:15
Description: Gendustry config loading failed in file jar:file:/home/taki/.tcraft/vanilla164/mods/gendustry-mc164-1.1.2.71.jar!/assets/gendustry/config/recipes.cfg: Config parsing failed at 21.15: `_' expected but`(' found

java.lang.RuntimeException: Config parsing failed at 21.15: `_' expected but`(' found
    at scala.sys.package$.error(package.scala:27)
    at net.bdew.lib.recipes.RecipeParser.doParse(RecipeParser.scala:126)
    at net.bdew.lib.recipes.RecipeLoader.load(RecipeLoader.scala:369)
    at net.bdew.gendustry.config.loader.TuningLoader$.tryLoadConfig(TuningLoader.scala:69)
    at net.bdew.gendustry.config.loader.TuningLoader$$anonfun$loadConfigFiles$1.apply(TuningLoader.scala:54)
    at net.bdew.gendustry.config.loader.TuningLoader$$anonfun$loadConfigFiles$1.apply(TuningLoader.scala:48)
    at scala.collection.immutable.List.foreach(List.scala:309)
    at net.bdew.gendustry.config.loader.TuningLoader$.loadConfigFiles(TuningLoader.scala:48)
    at net.bdew.gendustry.Gendustry$.preInit(Gendustry.scala:50)
    at net.bdew.gendustry.Gendustry.preInit(Gendustry.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Linux (amd64) version 3.2.0-4-amd64
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 252304120 bytes (240 MB) / 522190848 bytes (498 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 1 total; -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 Optifine OptiFine_1.6.4_HD_U_C8 50 mods loaded, 50 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{6.4.49.965} [Forge Mod Loader](Forge.jar) Unloaded->Constructed->Pre-initialized
    Forge{9.11.1.965} [Minecraft Forge](Forge.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.6.1.9} [Not Enough Items](NotEnoughItems%201.6.1.9.jar) Unloaded->Constructed->Pre-initialized
    AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    denLib{3.2.6} [denLib](minecraft.jar) Unloaded->Constructed->Pre-initialized
    DenEvents{1.0} [DenEvents](DenEvents.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{2.9.2.3} [Damage Indicators](1.6.4%20DamageIndicatorsv2.9.2.3.zip) Unloaded->Constructed->Pre-initialized
    mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap]([1.6.4]ReiMinimap_v3.4_01.zip) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    APUnofficial{2.6.0} [Additional Pipes](AdditionalPipes2.6.0-BC4.2.1.jar) Unloaded->Constructed->Pre-initialized
    AppliedEnergistics{rv14.finale3} [Applied Energistics](appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized
    bdlib{1.2.2.44} [BD Lib](bdlib-mc164-1.2.2.44.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{2.0.8} [Carpenter's Blocks](Carpenter's%20Blocks%20v2.0.8%20-%20MC%201.6+.zip) Unloaded->Constructed->Pre-initialized
    IC2{2.0.396-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.396-experimental.jar) Unloaded->Constructed->Pre-initialized
    ImmibisCore{57.2.0} [Immibis Core](immibis-core-57.2.0.jar) Unloaded->Constructed->Pre-initialized
    DimensionalAnchors{57.1.96} [Dimensional Anchors](dimensional-anchor-57.1.96.jar) Unloaded->Constructed->Pre-initialized
    Forestry{2.3.1.1} [Forestry for Minecraft](forestry-A-2.3.1.1.jar) Unloaded->Constructed->Pre-initialized
    gendustry{1.1.2.71} [GenDustry](gendustry-mc164-1.1.2.71.jar) Unloaded->Constructed
    GregsLighting{1.9.1} [Greg's Lighting](GregsLighting-1.9.1-mc1.6.4.jar) Unloaded->Constructed
    Railcraft{8.4.0.0} [Railcraft](Railcraft_1.6.4-8.4.0.0.jar) Unloaded->Constructed
    gregtech_addon{MC162} [GregTech-Addon](gregtechmod408s.zip) Unloaded->Constructed
    IronChest{5.4.1.702} [Iron Chest](ironchest-universal-1.6.4-5.4.1.702.zip) Unloaded->Constructed
    NEIAddons{1.10.5.70} [NEI Addons](neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
    NEIAddons|AE{1.10.5.70} [NEI Addons: Applied Energistics](neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
    NEIAddons|MiscPeripherals{1.10.5.70} [NEI Addons: Misc Peripherals](neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
    NEIAddons|ExtraBees{1.10.5.70} [NEI Addons: Extra Bees](neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
    NEIAddons|Forestry{1.10.5.70} [NEI Addons: Forestry](neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
    NEIAddons|CraftingTables{1.10.5.70} [NEI Addons: Crafting Tables](neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
    NEIAddons|ExNihilo{1.10.5.70} [NEI Addons: Ex Nihilo](neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
    NEIPlugins{1.1.0.6} [NEI Plugins](NEIPlugins-1.1.0.6.jar) Unloaded->Constructed
    ForgeMultipart{1.0.0.244} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed
    ProjRed|Core{4.3.7.32} [ProjectRed](ProjectRedBase-1.6.4-4.3.7.32.jar) Unloaded->Constructed
    ProjRed|Transmission{4.3.7.32} [ProjectRed-Transmission](ProjectRedIntegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed
    ProjRed|Transportation{4.3.7.32} [ProjectRed-Transportation](ProjectRedMechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed
    ProjRed|Exploration{4.3.7.32} [ProjectRed-Exploration](ProjectRedWorld-1.6.4-4.3.7.32.jar) Unloaded->Constructed
    ProjRed|Compatibility{4.3.7.32} [ProjectRed-Compatibility](ProjectRedCompat-1.6.4-4.3.7.32.jar) Unloaded->Constructed
    ProjRed|Integration{4.3.7.32} [ProjectRed-Integration](ProjectRedIntegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed
    ProjRed|Illumination{4.3.7.32} [ProjectRed-Illumination](ProjectRedLighting-1.6.4-4.3.7.32.jar) Unloaded->Constructed
    ProjRed|Expansion{4.3.7.32} [ProjectRed-Expansion](ProjectRedMechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed
    QuarryPlus{1.0.0} [QuarryPlus](QuarryPlus-1.6.4-1.0.3.jar) Unloaded->Constructed
    TelePipes{1.0.0} [Teleport Pipes](TeleportPipes-Pre1c.zip) Unloaded->Constructed
    McMultipart{1.0.0.244} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed
    ForgeMicroblock{1.0.0.244} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed

**Comment by bdew** [comment]
This crash makes no sense to me whatsoever. Try redownloading (maybe something got corrupted) and if that doesn't help please post a full log (ForgeModLoader-client-0.log)

**Comment by takilazy** [comment]
Full log, server with this mod starts, but the config file in the config folder is not created. But client crushing.
http://pastebin.com/KZfjYAnD

**Comment by bdew** [comment]
Still doesn't make any sense to me. It fails to process the internal config but i can't reproduce that with the same versions. Did you download it from my site/jenkins? did you try redownloading?

**Comment by takilazy** [comment]
Yes, from Jenkins. I trying 2 last versions and client don't run, I'll try to run with a ic2 bc and forestry in case of conflict with other mods, then write about what will happen.

**Comment by takilazy** [comment]
sorry for the long answer, with a minimum of mods still crash, I think it's because of i use the unofficial launcher.

**Comment by Tankistodor** [comment]
I have a similar problem with this mod. Startup whith JMClauncher.

**Comment by bdew** [comment]
Can you give me a link to this launcher? Google doesn't give useful results.

I still don't understand what's going on here and can't reproduce the crash.

**Comment by bdew** [comment]
Can't reproduce and no response from orinial reporter so i'm closing this.
