### ISSUE TITLE
Server crashing with Ticking entity issue

### ISSUE THREAD

**Issue by DatenThielt** [bdew-minecraft/gendustry#60]
Hey all. Using the latest version of Gendustry,  Our server crashes about twice a day.  Stack Trace below.  Appears to be related to stack movement, Thanks!

-- Head --
Stacktrace:
 at net.minecraft.item.ItemStack.func_77981_g(ItemStack.java:223)
 at net.bdew.lib.items.ItemUtils$.isSameItem(ItemUtils.scala:45)
 at net.bdew.lib.items.ItemUtils$$anonfun$addStackToSlots$1.apply$mcZI$sp(ItemUtils.scala:54)
 at net.bdew.lib.items.ItemUtils$$anonfun$addStackToSlots$1.apply(ItemUtils.scala:54)
 at net.bdew.lib.items.ItemUtils$$anonfun$addStackToSlots$1.apply(ItemUtils.scala:54)
 at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
 at scala.collection.immutable.Range.foreach(Range.scala:160)
 at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
 at net.bdew.lib.items.ItemUtils$.addStackToSlots(ItemUtils.scala:54)
 at net.bdew.gendustry.machines.apiary.TileApiary.addProduct(TileApiary.scala:256)
 at forestry.apiculture.BeekeepingLogic.update(BeekeepingLogic.java:185)
 at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2.apply$mcV$sp(TileApiary.scala:115)
 at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
 at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
 at scala.collection.immutable.List.foreach(List.scala:383)
 at net.bdew.lib.Event0.trigger(Event.scala:19)
 at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)

**Comment by bdew** [comment]
It looks like something is producing invalid ItemStacks... Are you using any other bee-adding mods?

**Comment by bdew** [comment]
Try this version: http://jenkins.bdew.net/job/gendustry-1.7.10/42/artifact/build/libs/gendustry-mc1710-1.4.0.42.jar

If it stops the crashes, look in your log for "Industrial Apiary at ...... received an invalid bee product" and the next line and report to whomever added that bee.

**Comment by DatenThielt** [comment]
Will give that a go, Thanks!

**Comment by DatenThielt** [comment]
Sorry just want to add,  (After looking at the code changes)  The check put in is for invalid bee Types.  We have replicated this using a Ferrous bee from Forestry, It had been using the automation upgrade and was a pure bee bred with all 13 chromosomes, Which was working for about a week.  We will implement this and report back :)

**Comment by bdew** [comment]
Ferrous  are from Magic Bees i think?

**Comment by DatenThielt** [comment]
Ahh, Ferrous are Thaumic sorry

**Comment by DatenThielt** [comment]
I did a local test with 4 apiaries, Same bee's in each one (Once again with all 13 chromosomes the same) 3 of them were fine, One crashed the server, Queen disappeared :+1:  This is befor the patch implimentation ofc

**Comment by bdew** [comment]
I assume this is fixed (as much as it can be fixed from my side) right?

**Comment by DatenThielt** [comment]
Sorry for the delay,  Afa I can tell it does appear to be resolved now. Thank you very much bDew!
