### ISSUE TITLE
Server crash: Ticking Block Entity

### ISSUE THREAD

**Issue by ruyanve** [bdew-minecraft/gendustry#62]
Versions used:
Buildcraft 6.1.5
Forestry 3.1.1.256
BDLib 1.5.1.32
Gendustry 1.4.1.43
Binnies Mod 2.0dev5

java.lang.NullPointerException: Ticking block entity
    at forestry.core.genetics.Chromosome.writeToNBT(Chromosome.java:65)
    at forestry.core.genetics.Genome.writeToNBT(Genome.java:85)
    at forestry.core.genetics.IndividualLiving.writeToNBT(IndividualLiving.java:68)
    at forestry.apiculture.BeekeepingLogic.update(BeekeepingLogic.java:212)
    at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2.apply$mcV$sp(TileApiary.scala:116)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at net.bdew.lib.Event0.trigger(Event.scala:19)
    at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Full crash log: http://pastebin.com/6AAiST0J

**Comment by bdew** [comment]
Looks like a bee with corrupted data, the crash happens in forestry code so not much i can do about it.

Does it keep crashing when you load the world? Do you know what bee it was and what was done with it before?

**Comment by ruyanve** [comment]
Nope, not on world load but about 1 min after the world has loaded. I know that one of my friends is using an industrial apiary, don't know what bee is in it tho. (he talked about the one that produces blaze powder, but I'm not positive if that's the one throwing the error)
Will find out by tonight.
Thank you for the quick reply!

**Comment by bdew** [comment]
FYI the apiary in question is at (453,64,2047)

If you can get to it and take the bee out before crashing, try sticking it in a beealizer - this will either crash (post the log if it does) or show you how broken it is :P

Also if your friend remembers what he did with it before it started crashing it might help figure out what caused it - either a bug in Extra Bees, a bug in Forestry or in one of my machines (if those were used on it)

**Comment by ruyanve** [comment]
Ok, after a couple of hours I got the damned bee out! :dancer: Server runs "fine" except some Forestry errors I need to report.

I've analyzed the bee and it gave me this: http://pastebin.com/9NXiN2DK

**Comment by ruyanve** [comment]
Seems to be on Forestrys end, build 256 introduced a bug regarding NBT data not being properly written. Closed for now
