### ISSUE TITLE
error on open a apiary with energy

### ISSUE THREAD

**Issue by krakel** [bdew-minecraft/gendustry#68]
I got a exception on open a apiary with energy.
Without energy I can open the gui.

java.lang.NoClassDefFoundError: Could not initialize class net.bdew.gendustry.machines.apiary.ErrorCodes$
at net.bdew.gendustry.machines.apiary.WidgetError.draw(WidgetError.scala:28)
at net.bdew.lib.gui.WidgetContainer$$anonfun$draw$1.apply(WidgetContainer.scala:64)
at net.bdew.lib.gui.WidgetContainer$$anonfun$draw$1.apply(WidgetContainer.scala:63)
at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
at scala.collection.mutable.MutableList.foreach(MutableList.scala:29)
at net.bdew.lib.gui.WidgetContainer$class.draw(WidgetContainer.scala:63)
at net.bdew.lib.gui.WidgetContainerWindow.draw(WidgetContainer.scala:81)
at net.bdew.lib.gui.BaseScreen.func_146979_b(BaseScreen.scala:48)
at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
at net.bdew.lib.gui.BaseScreen.func_73863_a(BaseScreen.scala:51)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by bdew** [comment]
Is this with forestry 3.2.0?

**Comment by bdew** [comment]
Nevermind, i guess you are on latest unstable and there backwards-incompatible changes over there.

Going back to Forestry unstable build 277 or stable 3.2.0 should fix it until i can get a fixed version out.

**Comment by krakel** [comment]
We are using forestry_1.7.10-3.1.1.283-unstable.jar with gendustry-mc1710-1.4.1.43.jar. It's the technicpack.net packet ProjectRETv7. I will talk with our admins.

**Comment by bdew** [comment]
This version should work with the latest unstable builds of forestry - http://jenkins.bdew.net/job/gendustry-1.7.10-fu/

**Comment by krakel** [comment]
fixed, thank you
