### ISSUE TITLE
mouseover energy bar kill minecraft

### ISSUE THREAD

**Issue by krakel** [bdew-minecraft/gendustry#73]

**Comment by bdew** [comment]
log?

**Comment by bdew** [comment]
Also if you are using bdlib 1.5.2 from jenkins - gendustry is not updated for it yet, downgrade to 1.5.1.

**Comment by krakel** [comment]
Sorry for the missing info.
Mod Pack: Technic - ProjectRETv7
bdlib-mc1710-1.5.2.33.jar
gendustry-mc1710-1.4.3.47.jar
The error occurs on all machine gui's by mouseover the energy bar. (a simple format problem)

I will discuss the bdlib problem with our OPs. 

java.lang.NoSuchMethodError: net.bdew.gendustry.gui.WidgetPowerCustom.formater()Ljava/text/DecimalFormat;
    at net.bdew.gendustry.gui.WidgetPowerCustom.handleTooltip(WidgetPowerCustom.scala:20)
    at net.bdew.lib.gui.WidgetContainer$$anonfun$handleTooltip$2.apply(WidgetContainer.scala:71)
    at net.bdew.lib.gui.WidgetContainer$$anonfun$handleTooltip$2.apply(WidgetContainer.scala:70)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.mutable.MutableList.foreach(MutableList.scala:29)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
    at net.bdew.lib.gui.WidgetContainer$class.handleTooltip(WidgetContainer.scala:70)
    at net.bdew.lib.gui.WidgetContainerWindow.handleTooltip(WidgetContainer.scala:81)
    at net.bdew.lib.gui.BaseScreen.func_73863_a(BaseScreen.scala:55)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by bdew** [comment]
Yeah that's what i thought. Either upgrade gendustry (and advanced generators, pressure pipes) to the latest versions from jenkins or downgrade bdlib to to the current stable version (1.5.1)
