### ISSUE TITLE
Forestry 3.3.0.6 + GenDustry 1.4.5.56 = crash

### ISSUE THREAD

**Issue by hron84** [bdew-minecraft/gendustry#80]
Log:

```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: forestry/api/core/IErrorState
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: forestry/api/core/IErrorState
    at net.bdew.gendustry.Gendustry$.preInit(Gendustry.scala:67)
    at net.bdew.gendustry.Gendustry.preInit(Gendustry.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: forestry.api.core.IErrorState
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 46 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.13.0-44-generic
    Java Version: 1.7.0_76, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 829217664 bytes (790 MB) / 1697120256 bytes (1618 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 3 total; -Xms1536m -Xmx2048m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1283 Minecraft Forge 10.13.2.1283 134 mods loaded, 133 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1283} [Forge Mod Loader] (forge-1.7.10-10.13.2.1283-universal.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1283} [Minecraft Forge] (forge-1.7.10-10.13.2.1283-universal.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997Core{1.0.2.9} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.9.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized
    ArmorStatusHUD{1.27} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized
    StatusEffectHUD{1.26} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.26.jar) Unloaded->Constructed->Pre-initialized
    act{0.0.2a_1.7.10} [AdminCommandsToolbox] (AdminCommandsToolbox-0.0.2a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    AppleCore{1.0.0} [AppleCore] (AppleCore-mc1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics2-rv2-beta-8.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997CoreHelper{1.0.2.9} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.9.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized
    asielib{0.3.9} [asielib] (AsieLib-1.7.10-0.3.9.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.4.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Automagy{0.17.1} [Automagy] (Automagy-1.7.10-0.17.1.jar) Unloaded->Constructed->Pre-initialized
    bdlib{1.6.2.41} [BD Lib] (bdlib-mc1710-1.6.2.41.jar) Unloaded->Constructed->Pre-initialized
    BetterChests{1.1.1.4} [BetterChests] (BetterChests-1.7.10-1.1.1.4.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.8.1} [BiblioCraft] (BiblioCraft[v1.8.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    ExtrabiomesXL{3.16.1} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.1.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.654-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.654-experimental.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.3.6} [BuildCraft] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsForestry{1.5} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.5].jar) Unloaded->Constructed->Pre-initialized
    BigReactors{0.4.0rc8} [Big Reactors] (BigReactors-0.4.0rc8.jar) Unloaded->Constructed->Pre-initialized
    BinnieCore{2.0-pre5} [Binnie Core] (binnie-mods-2.0-pre5.jar) Unloaded->Constructed->Pre-initialized
    Botany{2.0-pre5} [Botany] (binnie-mods-2.0-pre5.jar) Unloaded->Constructed->Pre-initialized
    ExtraBees{2.0-pre5} [Extra Bees] (binnie-mods-2.0-pre5.jar) Unloaded->Constructed->Pre-initialized
    ExtraTrees{2.0-pre5} [Extra Trees] (binnie-mods-2.0-pre5.jar) Unloaded->Constructed->Pre-initialized
    Genetics{2.0-pre5} [Genetics] (binnie-mods-2.0-pre5.jar) Unloaded->Constructed->Pre-initialized
    qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.69-universal.jar) Unloaded->Constructed->Pre-initialized
    bluepower{0.2.835} [Blue Power] (BluePower-1.7.10-0.2.835-universal.jar) Unloaded->Constructed->Pre-initialized
    Botania{r1.4-157} [Botania] (Botania r1.4-157.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.3.6} [BC Transport] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.3.6} [BC Silicon] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.3.6} [BC Builders] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.3.6} [BC Energy] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.3.6} [BC Factory] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.2.8} [Carpenter's Blocks] (Carpenter's Blocks v3.2.8 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    chisel{2.3.5.005a8c5} [Chisel 2] (Chisel2_DEV-2.3.5.005a8c5.jar) Unloaded->Constructed->Pre-initialized
    CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed->Pre-initialized
    ComputerCraft{1.64} [ComputerCraft] (ComputerCraft1.64.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.2.7.326} [Ender IO] (EnderIO-1.7.10-2.2.7.326.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.null} [EnderStorage] (EnderStorage-1.7.10-1.4.5.X.3-MR208.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers{1.4.7a.32} [OpenComputers] (OpenComputers-MC1.7.10-1.4.7a.32-universal.jar) Unloaded->Constructed->Pre-initialized
    computronics{1.4.0} [Computronics] (Computronics-1.7.10-1.4.0.jar) Unloaded->Constructed->Pre-initialized
    EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (EasyCrafting-1.7.10-2.0.1.16.jar) Unloaded->Constructed->Pre-initialized
    eplus{1.7.10-3.0.0a2} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.0a2.jar) Unloaded->Constructed->Pre-initialized
    Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized
    extracells{2.2.53} [ExtraCells] (ExtraCells-1.7.10-2.2.53b82.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins187} [Mantle] (Mantle-1.7.10-0.3.2.jenkins187.jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.8.2.build877} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2.build877.jar) Unloaded->Constructed->Pre-initialized
    ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    FastCraft{1.11} [FastCraft] (fastcraft-1.11.jar) Unloaded->Constructed->Pre-initialized
    ganyssurface{1.9.5} [Gany's Surface] (Ganys Surface-1.9.5.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized
    MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized
    gendustry{1.4.5.56} [GenDustry] (gendustry-mc1710-1.4.5.56.jar) Unloaded->Constructed->Errored
    Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
    harvestcraft{1.7.10b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10b.jar) Unloaded->Constructed->Pre-initialized
    HungerOverhaul{1.7.10-beta.2.jenkins30} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.2.jar) Unloaded->Constructed->Pre-initialized
    IC2NuclearControl{2.0.8c} [Nuclear Control 2] (IC2NuclearControl-2.0.8c.jar) Unloaded->Constructed->Pre-initialized
    inpure|core{1.7.10R1.0.0B1} [INpureCore] (INpureCore-[1.7.10]1.0.0B2-4.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    LogisticsPipes{0.8.3.100} [Logistics Pipes] (logisticspipes-0.8.3.100.jar) Unloaded->Constructed->Pre-initialized
    Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.133.jar) Unloaded->Constructed->Pre-initialized
    MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.133.jar) Unloaded->Constructed->Pre-initialized
    MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.133.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.2.9} [NEI Addons] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] (NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized
    OpenPeripheralCore{0.5.0} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded->Constructed->Pre-initialized
    OpenPeripheral{0.2.0} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized
    OpenPeripheralIntegration{0.1.0} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded->Constructed->Pre-initialized
    fodc{1.5.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.5.2.jar) Unloaded->Constructed->Pre-initialized
    clayspawn{1.7.2a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.7.2a.zip) Unloaded->Constructed->Pre-initialized
    RandomThings{2.1.4} [Random Things] (RandomThings-2.1.4.jar) Unloaded->Constructed->Pre-initialized
    StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized
    StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) Unloaded->Constructed->Pre-initialized
    TiCTooltips{1.2.1} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    WailaHarvestability{1.1.1} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.1.jar) Unloaded->Constructed->Pre-initialized
    wawla{1.1.0} [What Are We Looking At] (Wawla-1.1.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized
    YALSM{2.1.3} [Yet Another Leather Smelting Mod] (yalsm-2.1.3.jar) Unloaded->Constructed->Pre-initialized
    Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized
    craftingmanager{1.0.7} [Crafting Manager] (zzzz_CraftingManager ALPHA 1.0.11 mc1.7.10.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    IguanaTweaksTConstruct{1.7.10-2.1.2.103} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.2.103.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    craftingmanagercore{1.0.7} [Crafting Manager Core] (minecraft.jar) Unloaded->Disabled
    OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
    AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
[14:49:51] [Client thread/WARN] [FML]: =============================================================
[14:49:51] [Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[14:49:51] [Client thread/WARN] [FML]: Offendor: org/multimc/EntryPoint.main([Ljava/lang/String;)V
[14:49:51] [Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[14:49:51] [Client thread/WARN] [FML]: =============================================================
[14:49:51] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# /home/ggarami/.multimc/instances/MagiCraft/minecraft/crash-reports/crash-2015-02-13_14.49.51-client.txt
Minecraft exited with exitcode 255.
```

**Comment by bdew** [comment]
Gendustry 1.4.5 requires forestry Forestry 3.4.0+

**Comment by hron84** [comment]
@bdew could you please update the website then? 

```
Requirements
Minecraft 1.7.10
Forge >= 10.13.0.1207
Forestry >= 3.3.0
```

**Comment by bdew** [comment]
Fixed, thanks for pointing this out
